### ISSUE TITLE
How to obtain train_1perc.pt

### ISSUE THREAD

**Issue by ykzhang-eeis** [emadeldeen24/CA-TCC#1]
![image](https://github.com/emadeldeen24/CA-TCC/assets/54619352/b431d630-fa83-4d1c-8abf-70186ae7a5e9)

**Comment by Bilz-Git** [comment]
Hi, 
@ykzhang-eeis and @emadeldeen24  Can you tell me how did you resolve this issue "How to obtain train_1perc.pt"? I would be very grateful.
