### ISSUE TITLE
Format of the dataset

### ISSUE THREAD

**Issue by Arist-hbnm** [emadeldeen24/CA-TCC#2]
Thank you very much for providing the code, but due to the lack of format details for data storage, I am unable to reproduce the training. Therefore, could you please provide an introduction to the storage details of the data or upload the file. Contact email: honggangyang97@gmail.com

**Comment by emadeldeen24** [comment]
Datasets details are the same as in [TS-TCC work](https://github.com/emadeldeen24/TS-TCC)
