### ISSUE TITLE
About Data Preprocessing

### ISSUE THREAD

**Issue by zhukaijie98** [emadeldeen24/CA-TCC#5]
I had a problem running CA-TCC, and I was working with UCI datasets.I've read the（https://github.com/emadeldeen24/eval_ssl_ssc/blob/main/split_k-fold_and_few_labels.py），I still don't understand how to handle this step when using UCI data sets. Could you help me？

**Comment by emadeldeen24** [comment]
You don't have to use that file. You just need to provide a few labeled data in any way.
