### ISSUE TITLE
Regarding the dataset

### ISSUE THREAD

**Issue by Sleep226** [emadeldeen24/CA-TCC#6]
Dear author, hello. If you have time, I have three questions to ask you:
1. How many training modes should I run in order to run CATCC? Should we follow the order in your. sh file 【 "self_Superserved" 】
"train_linear_1p"
"ft_1p"
"gen_pseudo_labels"
"SupCon"
Train_inear_SupCon_1p
How about running it like this? So which running result is the final result of the model?
2. If I want to use my own dataset to run the CATCC model. My dataset is also time series data, with a total of about 5000 pieces of data, which means there are 5000 samples. Half of them have labels, while the other half have no labels.
In the initial self supervision section, should I use all 5000 of my data to run self supervision, then fine tune it with 2500 labeled data, label the remaining 2500 unlabeled data with pseudo labels, and use the 2500 labeled data for final training (or should I use all 5000 data for final training).
Or should I use my 2500 unlabeled data in the initial self supervised section to run the self supervised mode?
3. Normally, unlabeled data and labeled data should be two different types of data. Did you do this in revising the article CATCC?

**Comment by emadeldeen24** [comment]
1. The steps are mentioned in the [shell script](https://github.com/emadeldeen24/CA-TCC/blob/main/ca_tcc_pipeline.sh). Results are in the final phase.

2. Yes, in the initial self-supervised phase, you can use the 5k samples. The steps you mentioned are right. Use the 5k labeled samples in the final phase of training.

3. If data has different distributions, you can consider the domain adaptation scenario, where you have a labeled source domain and unlabeled shifted target domain. I have many works that consider this scenario with github codes. Check AdaTime for start.

Also, the different labeling scenarios linked to their solutions are mentioned in [my review paper](https://arxiv.org/pdf/2302.06433).
