### ISSUE TITLE
Hello！ When reading the article, I found that the results of CATCC in Table 4 on the HAR dataset were inconsistent with those in sensitivity analysis Figure 8 (c) on the HAR dataset. I would like to know why this is the case. 

### ISSUE THREAD

**Issue by zjuml** [emadeldeen24/CA-TCC#9]
Hello！ When reading the article, I found that the results of CATCC in Table 4 on the HAR dataset were inconsistent with those in sensitivity analysis Figure 8 (c) on the HAR dataset. I would like to know why this is the case.

**Comment by emadeldeen24** [comment]
Fig. 8 is done with full labels. Table 4 is with 1% and 5% of labels.
